apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.account.name }}
  namespace: {{ .Values.nfs.namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: {{ .Values.account.role }}
   namespace: {{ .Values.nfs.namespace }}
rules:
   -  apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["get", "list", "watch", "create", "delete"]
   -  apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "watch", "update"]
   -  apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
   -  apiGroups: [""]
      resources: ["events"]
      verbs: ["watch", "create", "update", "patch"]
   -  apiGroups: [""]
      resources: ["services", "endpoints"]
      verbs: ["get","create","list", "watch","update"]
   -  apiGroups: ["extensions"]
      resources: ["podsecuritypolicies"]
      resourceNames: ["nfs-provisioner"]
      verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.account.bind }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.account.name }}
    namespace: {{ .Values.nfs.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.account.role }}
  apiGroup: rbac.authorization.k8s.io